Bugfix : Uppercase 'NONE' creates a problem during the YAML files generation
acl-org/acl-anthology pull request #1221
Opened 2021-02-22 11:38 UTC by halecakir

Uppercase 'NONE' creates a problem during the YAML files generation step.

The problem arises in **OSX**.

Let me explain the problem.
After cloning the repository, I run the below commands:
    1. make venv/bin/activate
    2. make build/.basedirs
    3. make build/.yaml

build/.yaml target produces people YAML files in build/data/people. As I understood, Anthology groups author data according to their first letter, and there are some papers without author info such as 'O09-2000' so you assign 'NONE' author id to these papers. OSX (HPS+ file system) does not support a case-sensitive file system so n.yaml and N.yaml files are the same. During the 'make build/.yaml' step, firstly, author names starting with 'n' produces the n.yaml file, finally, authors with NONE id (does not produces N.yaml) overrides n.yaml file.

Sorry for this long commit message. I hope I could explain and solved the problem.

2021-02-22 12:17 UTC, halecakir commented
Mr. @mbollmann, What do you think about the commit [501a249](https://github.com/acl-org/acl-anthology/pull/1221/commits/501a24920a9b349185ee8416ddfcf0d4805333f7)?
I wonder how it worked on your computer.

Installed Hugo in my mac:
Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown

2021-02-22 12:34 UTC, mbollmann requested changes
Thanks for the PR!

1. I agree with changing the slug to lower-case `none`, otherwise this is the only instance of upper-case letters in a slug.
2. The bug, if any, is that the `data-export/papers/` subdirectory is still created; the .bib files are created in the right place, cf. the `hugo/layouts/papers/single.html` template. Your change would cause them to no longer be linked on the website.

2021-02-22 13:37 UTC, halecakir commented
Commit=501a249 makes no problem in my environment. Anyway, I reverted it back to the previous version to prevent further problems in your environments.

2021-02-23 11:25 UTC, mbollmann commented
Thanks! To clarify:

> Commit=501a249 makes no problem in my environment. Anyway, I reverted it back to the previous version to prevent further problems in your environments.

It will build the website without errors, but the .bib links won't show up on the generated pages.

2021-02-23 11:25 UTC, mbollmann approved these changes

2021-02-23 11:27 UTC, merged