Ingestion: nsurl
acl-org/acl-anthology pull request #2488
Opened 2023-04-20 13:40 UTC by anthology-assist

2023-04-20 18:33 UTC, anthology-assist commented
Waiting for paper titles to be corrected by conf submitter.

2023-05-03 15:07 UTC, mjpost reviewed
Looks good, will approve when comments are addressed.

2023-05-03 15:07 UTC, mjpost commented on data/xml/2022.nsurl.xml
> +      <booktitle>Proceedings of the Third International Workshop on NLP Solutions for Under Resourced Languages (NSURL 2022) co-located with ICNLSP 2022</booktitle>
Please list as a colocated event in `2022.icnlsp.xml`.

2023-05-22 14:23 UTC, mjpost commented
Can we address these comments and get this merged?

2023-06-10 20:43 UTC, anthology-assist commented on data/xml/2022.nsurl.xml
> +  <volume id="3" ingest-date="2023-04-27">
done

2023-06-10 20:48 UTC, anthology-assist commented
Also removed wrong pdfs on server.

2023-06-16 05:22 UTC, mjpost commented on data/xml/2022.nsurl.xml
> +  <volume id="3" ingest-date="2023-04-27">
It still reads `id="3"`, and two volumes show up in the preview

2023-06-16 05:22 UTC, mjpost commented on data/xml/2022.nsurl.xml
> +    <meta>
Hmm, it seems you have the same volume here twice, once as id "3" and once as id "1".

2023-06-16 05:22 UTC, mjpost commented on data/xml/2022.nsurl.xml
> +      <booktitle>Proceedings of the third International Workshop on NLP Solutions for Under Resourced Languages (NSURL 2022) co-located with ICNLSP 2022</booktitle>
"Third"

2023-06-16 05:23 UTC, mjpost requested changes
Please note changes in review (duplicate volume, lowercase word in volume name)

2023-06-22 14:16 UTC, merged