Fix name for Eddie Antonio Santos
acl-org/acl-anthology pull request #4115
Opened 2024-12-04 17:37 UTC by eddieantonio

I'm fixing my name in the anthology. Please let me know if there are any other files to modify — but it seems that this successfully merges the two author profiles that have been created for me (i.e., for "[Santos, Eddie](https://aclanthology.org/people/e/eddie-santos/)" and "[Antonio Santos, Eddie](https://aclanthology.org/people/e/eddie-antonio-santos/)").

2024-12-04 18:45 UTC, nschneid requested changes
Thanks. Please also correct the metadata XML for papers so it matches the PDF:
https://aclanthology.org/2021.eacl-main.226/ and https://aclanthology.org/L16-1514/ PDFs say Eddie A. Santos
https://aclanthology.org/2020.sltu-1.12/ PDF says Eddie Antonio Santos

2024-12-04 23:23 UTC, eddieantonio commented
Done! Geez, I didn't realize how many inconsistencies my name could create!

2024-12-04 23:28 UTC, nschneid approved these changes

2024-12-05 12:27 UTC, merged

2024-12-05 12:27 UTC, mjpost commented
@eddieantonio you are one of many :) Thanks for doing the legwork by submitting the PR!